"""Elliptic curves tasks (2) implementation in python."""
from structures import affine

# Params of sample curve generated by sage script.
# TODO: Make it call docker as subprocess and automatically get params.
# Elliptic Curve defined by y^2 = x^3 + 236367012452*x + 74315650609
# over Finite Field of size 807368793739
# Order of the curve: 807369655039
# Basepoint in normalized projective coordinates:
# (172235452673 : 488838007757 : 1)


def main():
    affine.AffinePoint.random()


if __name__ == "__main__":
    main()
